services:
  api:
    build:
      context: ./microservice-project/api
      dockerfile: DockerFile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/learnto
      - SPRING_DATASOURCE_USERNAME=vishrutbhushan
      - SPRING_DATASOURCE_PASSWORD=not4u2c
    depends_on:
      mysql:
        condition: service_healthy
    entrypoint: ["sh", "-c", "sleep 30 && java -jar /usr/src/app/target/api-1.0-SNAPSHOT.jar"]

  ui:
    build:
      context: ./microservice-project/ui
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: not4u2c
      MYSQL_DATABASE: learnto
      MYSQL_USER: vishrutbhushan
      MYSQL_PASSWORD: not4u2c
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=not4u2c"]
      interval: 30s
      timeout: 10s
      retries: 10

volumes:
  db_data: