export const INSERT_NODE = "INSERT_NODE";
export const REMOVE_NODE = "REMOVE_NODE";
export const UPDATE_WEIGHT = "UPDATE_WEIGHT";
export const SET_SELECT_NODE = "SET_SELECT_NODE";
export const DESELECT_NODE = "DESELECT_NODE";
export const RESET = "RESET";
export const GET_WEIGHT = "GET_WEIGHT";
export const UPDATE_NODE_POSITION = "UPDATE_NODE_POSITION";
export const SET_HIGHLIGHT_LINK = "SET_HIGHLIGHT_LINK";
export const SET_HIGHLIGHT_NODE = "SET_HIGHLIGHT_NODE";
export const SET_SAVED_GRAPHS = "SET_SAVED_GRAPHS";
export const OPEN_SAVED_GRAPH = "OPEN_SAVED_GRAPH";

export const DELETE_GRAPH_REQUEST = "DELETE_GRAPH_REQUEST";
export const UPDATE_GRAPH_REQUEST = "UPDATE_GRAPH_REQUEST";
export const CREATE_GRAPH_REQUEST = "CREATE_GRAPH_REQUEST";
export const FETCH_GRAPH_REQUEST = "FETCH_GRAPH_REQUEST";
export const FETCH_GRAPHS_REQUEST = "FETCH_GRAPHS_REQUEST";

export const DISPLAY_NOTIFICATION = "DISPLAY_NOTIFICATION";